name: "reader"
backend: "onnxruntime" 
max_batch_size: 32 # Adjust as needed
input [
  {
    name: "input_ids"
    data_type: TYPE_INT64 # Or TYPE_INT32
    dims: [ -1, -1 ] 
  },
  {
    name: "attention_mask"
    data_type: TYPE_INT64 # Or TYPE_INT32
    dims: [ -1, -1 ] 
  }
]
output [
  {
    name: "start_logits"
    data_type: TYPE_FP32
    dims: [ -1, -1 ] 
  },
  {
    name: "end_logits"
    data_type: TYPE_FP32
    dims: [ -1, -1 ]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]